# Generated by Django 2.1.7 on 2019-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500)),
                ('exercise', models.BooleanField(default=False)),
                ('scale', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=(1, '1'))),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
